# Generated by Django 5.2.4 on 2025-12-03 18:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_cost',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_cols',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_rows',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 3, 18, 4, 10, 457375, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 3, 18, 4, 26, 414832, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField()),
                ('total_cols', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='auditorium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.auditorium'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_letter', models.CharField(max_length=5)),
                ('col_number', models.IntegerField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.auditorium')),
            ],
            options={
                'unique_together': {('auditorium', 'row_letter', 'col_number')},
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seat')),
            ],
        ),
    ]
