# Generated by Django 5.2.9 on 2025-12-04 17:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_created_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='event',
            name='auditorium',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='auditorium',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='seat',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_amount',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.TextField(default='', help_text="Comma-separated list of seat IDs, e.g. 'A1,A2'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2025, 12, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(17, 41, 4, 720795)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue_cols',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_rows',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Auditorium',
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
